### ISSUE TITLE
Primitive integer not validated correctly

### ISSUE THREAD

**Issue by rwalle61** [swagger-model-validator/swagger-model-validator#120]
Thanks for this great module! I have started using it, and there are just a few little issues I found.

I've recreated this in your test suite - it is failing but I think should be passing?
![image](https://user-images.githubusercontent.com/18170169/71383601-062b8a80-25d5-11ea-8eb2-8bc1bb62c80e.png)
see https://github.com/rwalle61/swagger-model-validator/commit/2d27d3aece65a7b2be7a1d1fde83419ff952c1f1

The tests in that file all test that you correctly validate object properties that should be integers, but not whether a primitive integer itself is correctly validated.

I believe this is the cause:
```js
if(targetType !== "object" && targetType !== modelType) {
        return createReturnObject(new Error('Unable to validate a model with a type: ' + targetType + ', expected: ' + modelType));
    }
```
 https://github.com/swagger-model-validator/swagger-model-validator/blob/master/lib/modelValidator.js#L89 

When `target` is an integer, `typeof target` is 'number', so `targetType` is 'number' but `modelType` is `integer`, so we throw this error

**Comment by brodyd** [comment]
This is not really designed to validate a single primitive.  It is intended to handle more complex json bodies than a single primitive type.

A single primitive type can be more easily validated in your code and doesn't really require swagger awareness.  This is more for the troublesome problems with an entire object being passed in.

**Comment by rwalle61** [comment]
I agree single primitive types are pretty easy to validate manually, and so a user wanting to validate their data could just do that.

However, your package is also useful for validating one's OpenAPI spec in automated tests. If I have an OpenAPI spec with this schema:
```
schemas:
    ProjectID:
        type: integer
```
Then the test above tests whether I have defined `ProjectID` correctly. 

This may seem a trivial test, because this `ProjectID` schema seems so easy to write, but this functionality would:
1. reduce confusion - a `ProjectID` schema with `type: number` passes but one with `type: integer` fails, which made me think for a moment that OpenAPI 3 did not support `type: integer`.
2. enable TDD of one's OpenAPI schema definitions. I could write my tests first, then make my OpenAPI docs match them, and then forever my tests and OpenAPI docs would be in sync.
3. make this package's validation API more complete and consistent, allowing others to build on top of it more easily. I'm developing a Chai plugin and want to let my users [validate their data against schema objects easily in Chai](https://github.com/RuntimeTools/chai-openapi-response-validator/issues/38). I want to satisfy points 1 and 2 above for them. That will require `validator.validate(123, { type: integer })` succeeding, and resolving issues https://github.com/swagger-model-validator/swagger-model-validator/issues/121 and https://github.com/swagger-model-validator/swagger-model-validator/issues/122 (which *are* about "the troublesome problems with an entire object being passed in")

What do you think?

**Comment by rwalle61** [comment]
I managed to fix this test by changing [`var targetType = typeof target`](https://github.com/swagger-model-validator/swagger-model-validator/blob/master/lib/modelValidator.js) to `var targetType = typeOf(target)`, `typeOf` being:
```js
function typeOf(variable) {
    if (Number.isInteger(variable)) {
        return 'integer';
    }
    return typeof variable;
}
```

But then that broke the `hasNumberRefTest` in `testRefModels1.js`. I was able to fix it by changing [`type: number`](https://github.com/swagger-model-validator/swagger-model-validator/blob/master/tests/testRefModels1.js#L88) to `type: integer`, but I think `type: number` ought to be passing if you supply an integer (OpenAPI docs: ["Note that integer as a type is also supported and is defined as a JSON number without a fraction or exponent part."](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types))

**Comment by brodyd** [comment]
I've looked into this and it is caused by a basic check at the top of the stack that assumes all types are objects at first and have properties that may be primitives or objects.
I'v made a change that will treat the root as a primitive or an object based on the model definition.
