### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by sandeepbonds** [swagger-model-validator/swagger-model-validator#124]
how do we do email validation.. tired by using format:email, that is not working
     "properties": {
              "name": {
                  "type": "string"
              },
              "address": {
                  "type": "string",
                  "format": "email"
              }
          }

**Comment by brodyd** [comment]
You can add a custom validator to the field if you want to validate email formatting.  I'll look at adding a format checker for emails though.

**Comment by brodyd** [comment]
I am looking at adding a very simple email validator that will ensure that any string defined with a format of email will pass if it has its first '@' character after the first character.

1@2 would pass as would 1@@@@@@@ even though these may not be a valid email.  I would suggest that if you want more robust email screening you would be better off performing a domain lookup check against the emails domain (and that is quite out of scope for this validator).
