### ISSUE TITLE
Incorrect variables in 'modelValidator' - 'allOf'

### ISSUE THREAD

**Issue by Krzychu81** [swagger-model-validator/swagger-model-validator#129]
Incorrect variables in 'allOf' with fix:

![Screen Shot 2020-01-14 at 11 03 34 am](https://user-images.githubusercontent.com/23515012/72302317-bb75cd80-36bd-11ea-8c47-4c7343d9f3eb.png)

Alternatively, do you accept pull requests?

**Comment by brodyd** [comment]
Arrrghhh!

**Comment by brodyd** [comment]
I certainly do accept pull requests - thank you very much for yours.
