### ISSUE TITLE
unable to create a `swagger client`

### ISSUE THREAD

**Issue by livneros** [swagger-model-validator/swagger-model-validator#148]
Hey.
On your installation guide, it is written that in order to create a validator, we should pass a `swagger client` into the `Validator` class:
```
Create a validator and pass your swagger client into it.

var Validator = require('swagger-model-validator');
var validator = new Validator(swagger);
```
can you please provide the creation/ initialization of your `swagger` object? i can't find any type of swagger objects that supplies the `validateModel` functionality as mentioned later on:

`var validation = swagger.validateModel("modelName", jsonObject, _allowBlankTarget_, _disallowExtraProperties_);`

**Comment by brodyd** [comment]
If you create a validator with a swagger object in it, it adds the validateModel to the swagger object.
If you don't do that you can call methods on the validator and pass in the swagger models.

**Comment by brodyd** [comment]
If you have one model call

var errors = validator.validate(data, model);

otherwise call

var errors = validator.validate(data, models["dataModel"], models);

Where you pass in the target model and the array of defined models so any sub models can be referenced.

**Comment by livneros** [comment]
Thanks for your quick response!
can you please provide the creation/ initialization of your swagger object as described here:
`var validator = new Validator(swagger);`
In addition, how should the `model` look like? (referenced on your Readme as `swaggerModel`)
Thanks a lot.

**Comment by brodyd** [comment]
The models are directly from swagger.  So they are the definitions accessed from the swagger definition.  It var ies based on the version of swagger.

It is either the swagger.allModels property for swagger 1.2, swagger.definitions for swagger 2.0, and swagger.components.schemas for OpenApi 3.0.

**Comment by brodyd** [comment]
You can checkout the tests to see examples of models.

`testSampleOk: function(test) {
        var model = {
            id: "TestModel",
            type: "object",
            required: [ "foo" ],
            properties: {
                foo: {
                    type: "object",
                    required: [ "event", "data" ],
                    properties: {
                        event: {
                            type: "string",
                            description: "name"
                        },
                        data: {
                            type: "object",
                            required: [ "email" ],
                            properties: {
                                email: {
                                    type: "string",
                                    description: "email address"
                                },
                                description: {
                                    type: "string",
                                    description: "description"
                                }
                            }
                        }
                    }
                }
            }
        };

        var data = {
            foo: {
                event: "test",
                data: {
                    email: "a@b.com"
                }
            }
        };

        var swagger = {
            definitions: {
                TestModel: model
            }
        };

        //noinspection JSUnusedLocalSymbols
        var testValidator = new Validator(swagger);

        var result = swagger.validateModel("TestModel", data);

        test.expect(1);
        test.ok(result.valid);
        test.done();
    }`
